import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { loadEnv } from "./lib/env.mjs";

const projectRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
loadEnv(projectRoot);

const deployTarget = process.env.DEPLOY_TARGET;
const backendServerPath = process.env.BACKEND_SERVER_PATH;

if (!deployTarget) {
  console.error("Missing DEPLOY_TARGET environment variable.");
  process.exit(1);
}

if (!backendServerPath) {
  console.error("Missing BACKEND_SERVER_PATH environment variable.");
  process.exit(1);
}

const requiredBackendEnv = [
  "ACTIVITYPUB_BASE_URL",
  "ACTIVITYPUB_DOMAIN",
  "ACTIVITYPUB_PUBLIC_KEY_PATH",
  "ACTIVITYPUB_PRIVATE_KEY_PATH"
];

for (const key of requiredBackendEnv) {
  if (!process.env[key]) {
    console.error(`Missing required environment variable: ${key}`);
    process.exit(1);
  }
}

function parseRsyncTarget(target) {
  const remoteMatch = target.match(/^([^:]+):(.*)$/);
  if (remoteMatch) {
    return {
      type: "remote",
      remote: remoteMatch[1],
      path: remoteMatch[2]
    };
  }

  return {
    type: "local",
    path: target
  };
}

function copyIntoStage(sourceRelativePath, targetRelativePath = sourceRelativePath) {
  const sourcePath = path.join(projectRoot, sourceRelativePath);
  const targetPath = path.join(stageRoot, targetRelativePath);
  const stat = fs.statSync(sourcePath);

  if (stat.isDirectory()) {
    fs.cpSync(sourcePath, targetPath, {
      recursive: true,
      filter: (source) => {
        const relativeFromSource = path.relative(sourcePath, source);
        if (!relativeFromSource) return true;
        return !relativeFromSource.startsWith(`data${path.sep}`) && relativeFromSource !== "data";
      }
    });
    return;
  }

  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.copyFileSync(sourcePath, targetPath);
}

function buildBackendEnvFile() {
  const keys = Object.keys(process.env)
    .filter((key) => key.startsWith("ACTIVITYPUB_"))
    .sort();

  const lines = ["# Generated by npm run deploy:backend"];

  for (const key of keys) {
    lines.push(`${key}=${process.env[key]}`);
  }

  return `${lines.join("\n")}\n`;
}

function runCommand(command, args, options = {}) {
  const result = spawnSync(command, args, {
    stdio: "inherit",
    ...options
  });

  if (result.status !== 0) {
    process.exit(result.status || 1);
  }
}

const stageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "cfde-backend-deploy-"));

try {
  copyIntoStage("backend");
  copyIntoStage("scripts/lib/env.mjs");
  copyIntoStage("scripts/activitypub-block-actor.mjs");
  copyIntoStage("scripts/activitypub-unblock-actor.mjs");
  copyIntoStage("scripts/activitypub-remove-follower.mjs");
  copyIntoStage("scripts/activitypub-retry-deliveries.mjs");
  copyIntoStage("package.json");
  copyIntoStage("package-lock.json");
  copyIntoStage("deploy/activitypub-backend.service");
  copyIntoStage("deploy/Caddyfile.activitypub");
  copyIntoStage("docs/ACTIVITYPUB_SERVER_SETUP.md");

  fs.writeFileSync(path.join(stageRoot, ".env"), buildBackendEnvFile(), "utf8");

  const parsedTarget = parseRsyncTarget(deployTarget);
  const rsyncArgs = [
    "-az",
    "--human-readable",
    "--progress"
  ];
  const extraArgs = (process.env.BACKEND_DEPLOY_RSYNC_ARGS || "").split(/\s+/).filter(Boolean);
  rsyncArgs.push(...extraArgs);

  if (parsedTarget.type === "remote") {
    runCommand("ssh", [parsedTarget.remote, "mkdir", "-p", backendServerPath]);
    rsyncArgs.push(`${stageRoot}/`, `${parsedTarget.remote}:${backendServerPath}/`);
  } else {
    fs.mkdirSync(backendServerPath, { recursive: true });
    rsyncArgs.push(`${stageRoot}/`, `${backendServerPath}/`);
  }

  runCommand("rsync", rsyncArgs);
} finally {
  fs.rmSync(stageRoot, { recursive: true, force: true });
}
